spring:
  application:
    name: remi-backend
  profiles:
    active: ${ENVIRONMENT:local}
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27016}/${MONGO_DB_NAME:test_db_2}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

app:
  jwtCookieName: remijwt
  jwtSecret: fruThlthup0hOc7taboCheqlhidamap4AwlPHlFrubljupoxlS7asahUbucU
  jwtExpirationMs: 86400000
  upload_path: ${UPLOAD_PATH:"/Users/vinodpatil/LAB/UPGRAD/Masters/FINAL_THESIS_WRITING/APP/REPOS/remi-backend-service/uploads"}

wireframe:
  baseurl: ${WIREFRAME_BASE:http://localhost:8000}
  boxdetection:
    endpoint: "/v1/findBoxes"

management:
  endpoints:
    web:
      exposure:
        include: info, health

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:${EUREKA_HOST_PORT:8761}/eureka/

  instance:
    hostname: ${API_GATE_WAY_END_POINT:localhost}
#    this above host used in eureka for trasport change to connectable host for this app
# like API gateway endpoint or localhost directly

swagger:
  url: "http://localhost:8080"
  description: "Development"
  author:
    name: "Vinod"
    email: "vinod0x01@gmail.com"
  info:
    title: "Remi Application API"
    version: "1.0"
    description: "Remi app api v1.0"

test_data_files:
  test_item: "src/main/resources/seed/test_items.json"
---


